export enum OrderStatus {
  NEW = 'NEW',
  PENDING_SUPPLIER = 'PENDING_SUPPLIER',
  ACCEPTED = 'ACCEPTED',
  PROCESSING = 'PROCESSING',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED'
}
