export enum OrderStatus {
  NEW = 'NEW',
  WAITING_FOR_SUPPLIER = 'WAITING_FOR_SUPPLIER',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  PREPARING = 'PREPARING',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}
