export enum FinancialEventType {
  PRICE_LOCKED = 'PRICE_LOCKED',
  DEBT_REGISTERED = 'DEBT_REGISTERED',
  PAYMENT_REGISTERED = 'PAYMENT_REGISTERED',
  ORDER_SETTLED = 'ORDER_SETTLED',
  REVERSAL = 'REVERSAL'
}
